const freshfood={
  "id": 260,
  "order": 5,
  "name": "Fresh, exclusive Fish and Seafood",
  "widgetName": "FnS Bestseller - NU",
  "type": "PRODUCT",
  "subText": "Caught on the same day",
  "iosEnabled": true,
  "androidEnabled": true,
  "webEnabled": true,
  "msiteEnabled": true,
  "layoutName": "product1",
  "status": "ACTIVE",
  "mappingType": "RULE_BASED",
  "widgetMediaType": "IMAGE",
  "ruleId": 4,
  "ruleDeeplink": "type=category%26category_id=1654",
  "widgetLayout": "CAROUSEL",
  "carouselType": "normal",
  "pageName": "homepage",
  "primaryIndex": 5,
  "contentType": "sm-product",
  "showViewAll": true,
  "products": [
    {
      "variantId": "pr_nqpkziiqt11",
      "productId": "prd-em1n9AIU2t7l",
      "name": "Freshwater Prawns (Medium Sized) - Cleaned & Deveined",
      "category": "Prawns",
      "weight": "500 g (Before cleaning/cutting)",
      "pieces": "20-30",
      "serves": "2-3",
      "basePrice": 465,
      "discountPercentage": 11,
      "discountedPrice": 412,
      "image": "https://cdn.licious.in/catalog/Banner/328x226_198%20White%20Prawns%20(40%2060C%20Medium)%20Cleaned%20Deveined%20(1).jpg",
      "usp": "Eral/Etti/Raatu/Chemmeen"
    },
    {
      "variantId": "pr_6j4jhlmxsk1",
      "productId": "prd-R7CbYRoZMPgb",
      "name": "Rohu (1.4kg) - Bengali Cut, No Head",
      "category": "Fish",
      "weight": "950 g (Before cleaning/cutting)",
      "pieces": "7-12",
      "serves": "2-3",
      "basePrice": 309,
      "discountPercentage": 20,
      "discountedPrice": 247,
      "image": "https://cdn.licious.in/catalog/Banner/328x226_248%20Rohu%20Fish%20Medium%20BC%20w%20o%20Head.jpg",
      "usp": "Kannadi kendai/Reba/Rui"
    },
    {
      "variantId": "pr_57235831e3960",
      "productId": "prd-SJ9JdG3NQ00W",
      "name": "Mackerel Medium - Whole Cleaned & Gutted",
      "category": "Fish",
      "weight": "700 g (Before cleaning/cutting)",
      "pieces": "2-4",
      "serves": "2-3",
      "basePrice": 639,
      "discountPercentage": 33,
      "discountedPrice": 427,
      "image": "https://cdn.licious.in/catalog/catalog-category/2af2726c-05f7-c75c-b1f2-4e3b7668bb57/original/1740573114595.jpg",
      "usp": "Bangda/Kanangeluthi/Kanakatha/Ayala"
    },
    {
      "variantId": "pr_gi9kauyla8l",
      "productId": "prd-em1n9AIU2t7l",
      "name": "Freshwater Prawns (Small Sized) - Cleaned and Deveined",
      "category": "Prawns",
      "weight": "500 g (Before cleaning/cutting)",
      "pieces": "40-55",
      "serves": "4-5",
      "basePrice": 425,
      "discountPercentage": 12,
      "discountedPrice": 374,
      "image": "https://cdn.licious.in/catalog/Banner/328x226_201%20White%20Prawns%20(80C%20Small)%20Cleaned%20Deveined.jpg",
      "usp": "Eral/Etti/Raatu/Chemmeen"
    },
    {
      "variantId": "pr_6j4jhlmzwle",
      "productId": "prd-FxueQZTIlavX",
      "name": "Catla (1.5kg) - Bengali Cut, No Head",
      "category": "Fish",
      "weight": "950 g (Before cleaning/cutting)",
      "pieces": "6-9",
      "serves": "3-4",
      "basePrice": 409,
      "discountPercentage": 23,
      "discountedPrice": 315,
      "image": "https://cdn.licious.in/catalog/Banner/328x226_229%20Freshwater%20Catla%20Bengali%20Cut%20Without%20Head.jpg",
      "usp": "Theppu Meen/Kendai/ Thoppu Meen/ Kanavi/Katla"
    }
  ]
}
export default freshfood